# Generated by Django 3.0.5 on 2020-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_auto_20200527_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
